function UpdateTrialinfo(sbj_name,dirs, project_name, datatype, freq_band, data_replace, tag)
% this function updates the trialinfo in the psychdata folder and in the
% epoched data files with additional fields for data analysis not predicted
% when data was first epoched.
%% INPUTS:
%       sbj_name: subject name
%       block_names: blocks to be analyed (cell of strings)
%       dirs: directories pointing to files of interest (generated by InitializeDirs)
%       project_name = name of the task (i.e. MMR)
%       datatype: 'CAR','HFB',or 'Spec'
%       tag: tag in filename between data type and block name, specifying which type of data to load (e.g. 'stimlock_bl_corr')


% data_replace = {'psychData', datatype};


% Get block names and electrodes
block_names = BlockBySubj(sbj_name,project_name);
load(sprintf('%s/originalData/%s/global_%s_%s_%s.mat',dirs.data_root,sbj_name,project_name,sbj_name,block_names{1}),'globalVar');
elecs = setdiff(1:globalVar.nchan,globalVar.refChan);

for i = 1:length(data_replace)
    
    for bi = 1:length(block_names)
        bn = block_names{bi};
        dir_in = [dirs.data_root,filesep,datatype,'Data',filesep,freq_band,filesep,sbj_name,filesep,bn,filesep,'EpochData'];
        if ~strcmp(data_replace{i}, 'psychData')
            for el = 1:length(elecs)
                load(sprintf('%s/%siEEG_%s_%s_%.2d.mat',dir_in,freq_band,tag,bn,el));
                data.trialinfo = UpdateTrialinfoParams(data.trialinfo, project_name);
                sprintf('updating trialinfo of electrode: %s_%s_%s_%.2d.mat',freq_band,tag,bn,el)
                save(sprintf('%s/%siEEG_%s_%s_%.2d.mat',dir_in,freq_band,tag,bn,el), 'data');
            end
        else
            % load trialinfo
            load([dirs.psych_root,filesep,sbj_name,filesep,bn,filesep,'trialinfo_',bn,'.mat'])
            trialinfo = UpdateTrialinfoParams(trialinfo, project_name);
            save([dirs.psych_root,filesep,sbj_name,filesep,bn,filesep,'trialinfo_',bn,'.mat'], 'trialinfo')
        end
        
    end
end

end

